version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

python:
  # Install our python package before building the docs
  install:
    - requirements: ./requirements.txt

formats:
  - pdf
  - epub
