version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
formats:
  - pdf
  - epub
